### ISSUE TITLE
Property `convert-policy-cedar-to-json` fails

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar-spec#341]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

Consider the following two Cedar policies that are accepted or rejected by the parser,
```cedar
// check-parse succeeds
// policy 1
permit(
  principal,
  action,
  resource
) when {
  ip(context, 0)
};
```

```cedar
// check-parse fails: `ip` is a function, not a method
// policy 2
permit(
  principal,
  action,
  resource
) when {
  context.ip(0) 
};
```

Both have the following EST representation,

```JSON
{
  "effect": "permit",
  "principal": {
    "op": "All"
  },
  "action": {
    "op": "All"
  },
  "resource": {
    "op": "All"
  },
  "conditions": [
    {
      "kind": "when",
      "body": {
        "ip": [
          {
            "Var": "context"
          },
          {
            "Value": 0
          }
        ]
      }
    }
  ]
}
```

Policy 2 causes `convert-policy-cedar-to-json` to fail. We could let EST to AST conversion to fail on policy 2, which makes policy 1 the new counterexample to this property.

**Comment by john-h-kastner-aws** [comment]
Two solution come to mind:

1. Report the error during the cst -> est conversion step. We should prefer reporting errors in the est -> ast step where possible, but there just isn't enough information in the est in this case.
2. Update the fuzz target to only try the cst -> est -> ast path if cst -> ast succeeds. This is reasonable because our public API does not allow converting a policy to json if it hasn't successfully built the ast already. This would make the fuzz target less useful since it could only test that our primary parser does not admit any policies the est parser rejects. We wouldn't know if the the primary parser is rejecting policies it shouldn't.

**Comment by shaobo-he-aws** [comment]
Would it make sense to add a call style field to EST extension function calls?

**Comment by cdisselkoen** [comment]
The reason we don't is that we currently don't allow any functions to be declared with both styles (or different functions with the same name but different styles), so the name is sufficient to identify the function
